### ISSUE TITLE
dynamic linking to save rom

### ISSUE THREAD

**Issue by ghost** [pexcn/openwrt-udpspeeder#2]
It seems that the upstream makefile uses -static. Is it possible to override this and save rom space?

**Comment by pexcn** [comment]
Maybe, you can try it, change the `MAKE_FLAGS`.

Reference:
https://github.com/pexcn/openwrt-udpspeeder/blob/master/Makefile#L40
https://github.com/wangyu-/UDPspeeder/blob/branch_libev/makefile#L51-L60

**Comment by ghost** [comment]
Great! Thanks!
